# Generated by Django 3.2.10 on 2023-05-11 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdetails',
            name='confirm_password',
        ),
    ]
