# Generated by Django 4.1.4 on 2023-05-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0002_remove_customerdetails_confirm_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="userqr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurantid", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("qr", models.CharField(max_length=50)),
            ],
        ),
    ]
