# Generated by Django 4.1.4 on 2023-05-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0003_userqr"),
    ]

    operations = [
        migrations.AddField(
            model_name="userqr",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="userqr",
            name="email",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="userqr",
            name="qr",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
