# Generated by Django 4.1.4 on 2023-05-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0004_userqr_status_alter_userqr_email_alter_userqr_qr"),
    ]

    operations = [
        migrations.DeleteModel(
            name="userqr",
        ),
    ]
