# Generated by Django 4.1.4 on 2023-05-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0005_delete_userqr"),
    ]

    operations = [
        migrations.CreateModel(
            name="Userqr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurantid", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=50)),
                ("qrcode", models.CharField(max_length=50)),
                ("qrcodepath", models.CharField(max_length=50)),
                ("status", models.CharField(default="pending", max_length=50)),
            ],
        ),
    ]
