# Generated by Django 4.1.4 on 2023-05-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0007_tablebooking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Useroder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("restaurantid", models.CharField(max_length=100)),
                ("Tableno", models.CharField(max_length=100)),
                ("dishid", models.CharField(max_length=100)),
                ("dishcount", models.CharField(max_length=100)),
                ("dishprice", models.CharField(max_length=100)),
                ("TotalPrice", models.CharField(max_length=100)),
            ],
        ),
    ]
