# Generated by Django 4.1.4 on 2023-05-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0008_useroder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useroder",
            name="TotalPrice",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
