# Generated by Django 4.1.4 on 2023-05-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0009_alter_useroder_totalprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="useroder",
            name="Useremail",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
