# Generated by Django 4.1.4 on 2023-05-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0010_useroder_useremail"),
    ]

    operations = [
        migrations.AddField(
            model_name="useroder",
            name="dishname",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
