# Generated by Django 4.1.4 on 2023-05-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0011_useroder_dishname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userqr",
            name="qrcode",
        ),
        migrations.RemoveField(
            model_name="userqr",
            name="qrcodepath",
        ),
    ]
