# Generated by Django 3.2.10 on 2023-05-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0012_remove_userqr_qrcode_remove_userqr_qrcodepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=1)),
                ('table_number', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
