# Generated by Django 4.1.4 on 2023-05-18 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0013_waitlinglist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useroder",
            name="Tableno",
        ),
        migrations.RemoveField(
            model_name="useroder",
            name="TotalPrice",
        ),
        migrations.RemoveField(
            model_name="useroder",
            name="Useremail",
        ),
        migrations.RemoveField(
            model_name="useroder",
            name="dishcount",
        ),
        migrations.RemoveField(
            model_name="useroder",
            name="dishid",
        ),
        migrations.RemoveField(
            model_name="useroder",
            name="dishname",
        ),
        migrations.RemoveField(
            model_name="useroder",
            name="dishprice",
        ),
        migrations.RemoveField(
            model_name="useroder",
            name="restaurantid",
        ),
        migrations.AddField(
            model_name="useroder",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="useroder",
            name="total_cost",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="useroder",
            name="user_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.IntegerField(null=True)),
                ("restaurent_id", models.CharField(max_length=100)),
                ("dish_id", models.CharField(max_length=100)),
                ("dish_count", models.CharField(max_length=100)),
                ("table_number", models.CharField(max_length=100)),
                ("dish_name", models.CharField(max_length=100)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Customer.useroder",
                    ),
                ),
            ],
        ),
    ]
