# Generated by Django 4.1.4 on 2023-05-19 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Customer",
            "0014_remove_useroder_tableno_remove_useroder_totalprice_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="waitlinglist",
            name="time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
