# Generated by Django 4.1.4 on 2023-05-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0015_alter_waitlinglist_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Email", models.EmailField(max_length=254)),
                ("useremail", models.CharField(max_length=100)),
                ("cardno", models.CharField(max_length=100)),
                ("amount", models.CharField(max_length=100)),
                ("expirydate", models.CharField(max_length=100)),
                ("cvv", models.CharField(max_length=100)),
                ("dc", models.CharField(max_length=100)),
            ],
        ),
    ]
