# Generated by Django 4.1.4 on 2023-05-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0017_remove_paymentdetails_useremail"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdetails",
            name="cardname",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
