# Generated by Django 4.1.4 on 2023-05-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Customer", "0019_remove_paymentdetails_dc"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdetails",
            name="resid",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="paymentdetails",
            name="tablenumber",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
