# Generated by Django 3.2 on 2025-03-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0020_paymentdetails_resid_paymentdetails_tablenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userqr',
            name='status',
            field=models.CharField(default='True', max_length=50),
        ),
    ]
