# Generated by Django 3.2 on 2025-03-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0021_alter_userqr_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userqr',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
