# Generated by Django 3.2 on 2025-03-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0023_alter_userqr_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='qrcode',
            field=models.FileField(null=True, upload_to='static\\order_qr_codes'),
        ),
    ]
