# Generated by Django 3.2 on 2025-03-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0024_orderitem_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='key',
            field=models.BinaryField(null=True),
        ),
    ]
