# Generated by Django 3.2 on 2025-03-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0025_orderitem_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='key',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='qrcode',
        ),
        migrations.AddField(
            model_name='useroder',
            name='key',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='useroder',
            name='qrcode',
            field=models.FileField(null=True, upload_to='static\\order_qr_codes'),
        ),
    ]
