# Generated by Django 3.2 on 2025-03-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0027_auto_20250313_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroder',
            name='otp',
            field=models.IntegerField(null=True),
        ),
    ]
