# Generated by Django 3.2 on 2025-03-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0028_useroder_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroder',
            name='order_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
