# Generated by Django 3.2 on 2025-03-14 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0029_useroder_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='key',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.useroder'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='qrcode',
            field=models.FileField(null=True, upload_to='static\\order_qr_codes'),
        ),
    ]
