# Generated by Django 3.2.10 on 2023-05-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='addfood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantid', models.CharField(max_length=100)),
                ('foodname', models.CharField(max_length=100)),
                ('foodprice', models.CharField(max_length=100)),
            ],
        ),
    ]
