# Generated by Django 3.2.10 on 2023-05-15 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0003_rename_addfood_addfoodinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurantid', models.CharField(max_length=100)),
                ('memberscount', models.CharField(max_length=100)),
                ('tableno', models.CharField(max_length=100)),
                ('status', models.CharField(default='available', max_length=100)),
            ],
        ),
    ]
