# Generated by Django 4.1.4 on 2023-05-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0004_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrcode",
            name="restaurantname",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
