# Generated by Django 4.1.4 on 2023-05-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Restaurant", "0006_alter_restaurant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
